### ISSUE TITLE
Write Tektronix AWG driver

### ISSUE THREAD

**Issue by terrorfisch** [qutech/qc-toolkit#265]

**Comment by terrorfisch** [comment]
Currently there is an implementation in https://github.com/qutech/qupulse/tree/issues/265_tektronix_driver_rebased

This uses [TekAWG](https://github.com/qutech/TekAwg) as backend.

I consider switching to the QCoDeS-driver.

Pros:
 - One package less to maintain
 - Implemented use of file system

Cons:
 - QCoDeS dependency
 - A lot of model specific code. (Although, I am not shure that TekAWG works without)

**Comment by terrorfisch** [comment]
Use possibly faster format files and file transfer:

https://forum.tek.com/viewtopic.php?t=140633
https://forum.tek.com/viewtopic.php?t=140605

**Comment by terrorfisch** [comment]
```python
from qctoolkit.pulses import TablePT

entry_list = [(0, 0),
              (2000, 2, 'hold'),
              (4000, 3, 'linear'),
              (6000, 0, 'jump')]

template = TablePT(entries={'P1': entry_list})
template2 = TablePT(entries={'P2': entry_list})


# works!
seqr=RepetitionPT(template, 15)
p=seqr.create_program()
qawg.upload('qtest2', p, ['P1','P1', None, None], [None]*8, voltage_transformation = [lambda x:x ]*4, force=True)

# fails!
seqr=RepetitionPT(template, 5)
p=seqr.create_program()
qawg.upload('qtest2', p, ['P1','P1', None, None], [None]*8, voltage_transformation = [lambda x:x ]*4, force=True)
```
fails with
```
ERROR:qupulse.tektronix:Error during upload. Set synced to false
Traceback (most recent call last):
  File "d:\users\eendebakpt\qupulse\qupulse\hardware\awgs\tektronix.py", line 529, in upload
    self._upload(*args, **kwargs)
  File "d:\users\eendebakpt\qupulse\qupulse\hardware\awgs\tektronix.py", line 718, in _upload
    self._upload_parsed(name, tek_program)
  File "d:\users\eendebakpt\qupulse\qupulse\hardware\awgs\tektronix.py", line 667, in _upload_parsed
    self._upload_linked_sequencing_elements(positions, sequencing_elements, self._idle_program_index)
  File "d:\users\eendebakpt\qupulse\qupulse\hardware\awgs\tektronix.py", line 598, in _upload_linked_sequencing_elements
    assert len(positions) == len(sequencing_elements)
AssertionError
```

I will add a test for `_get_empty_sequence_positions`

Thanks @eendebakpt for reporting

**Comment by terrorfisch** [comment]
@reneotten Do you have experienced problems with the current driver?
